### ISSUE TITLE
Cannot iterate schema to use request definitions

### ISSUE THREAD

**Issue by shadowhand** [eleven-labs/api-validator#12]
I want to be able to iterate the schema and use all request definitions to help generate routes:

```php
$schema = (new SwaggerSchemaFactory())->createSchema($schemaPath);

foreach ($schema->getDefinitions() as $requestDefinition) {
    $router->add($requestDefinition->getMethod(), $requestDefinition->getPathTemplate(), $requestDefinition->getOperationId());
}
```

Currently this is not possible because there is no `Schema::getDefinitions()` method and no way to extract the definitions once they are inside of `Schema`.

**Comment by guillemcanal** [comment]
Hi, thanks for reporting this, it's indeed an interesting use case.  
You are very welcome to make a PR to support this feature. If you need guidance, don't hesitate :)

**Comment by shadowhand** [comment]
@guillemcanal PR made.
